CREATE DATABASE library;

USE library;

CREATE TABLE user (
	ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE book (
	ISBN VARCHAR(13) PRIMARY KEY,
    TITLE VARCHAR(150) NOT NULL,
    AUTOR VARCHAR(150) NOT NULL,
    AVAILABLE TINYINT DEFAULT 1
);

CREATE TABLE borrow_books (
	ID_BORROW_BOOKS INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER INT NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    DATA_BORROW DATETIME DEFAULT NOW(),
    DATA_RETURN DATETIME,
    CONSTRAINT FK_USER_BORROW_BOOKS FOREIGN KEY (ID_USER) REFERENCES user(ID_USER),
    CONSTRAINT FK_BOOK_BORROW_BOOKS FOREIGN KEY (ISBN) REFERENCES book(ISBN)
);